<a href="https://colab.research.google.com/github/roberthsu2003/machine_learning/blob/main/%E6%B3%95%E5%8B%99%E9%83%A8%E6%A9%9F%E5%99%A8%E5%AD%B8%E7%BF%92/%E5%A4%9A%E5%85%83%E7%B7%9A%E6%80%A7%E8%BF%B4%E6%AD%B8/multiple_linear_regression2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=d69a023893dd4a0ef67f8ef08de48726ea90e7b76bad119800c2f43fcf037874
  Stored in directory: /root/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget


In [2]:
import wget
url = "https://github.com/roberthsu2003/machine_learning/raw/refs/heads/main/source_data/Salary_Data2.csv"
#下載資料
wget.download(url)

#下載字型
wget.download("https://github.com/roberthsu2003/machine_learning/raw/refs/heads/main/source_data/ChineseFont.ttf")

'ChineseFont.ttf'

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import numpy as np

In [4]:
# 載入資料
url = "Salary_Data2.csv"
data = pd.read_csv(url)
data

YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

In [5]:
# Label Encoding for EducationLevel
le = LabelEncoder()
data['EducationLevel'] = le.fit_transform(data['EducationLevel'])
data

YearsExperience  EducationLevel City  Salary
0               3.0               0  城市A    45.9
1               7.8               1  城市C    80.5
2               2.3               2  城市A    25.2
3               5.1               2  城市A    30.4
4              10.0               1  城市B    65.7
5               1.2               1  城市C    60.8
6               8.6               0  城市C    50.1
7               6.9               1  城市A    70.3
8               4.2               0  城市A    40.7
9               2.4               2  城市A    28.1
10              5.3               2  城市A    32.0
11              3.9               0  城市A    48.3
12              7.2               1  城市C    84.2
13             10.0               1  城市B    70.9
14              1.5               1  城市C    62.4
15              8.4               0  城市C    55.6
16              6.5               1  城市A    72.7
17              4.8               0  城市A    42.9
18              2.1               2  城市A    26.5
19              5.2               2  城市A    31.6
20              3.5               0  城市A    43.8
21              7.6               1  城市C    78.3
22             10.0               1  城市B    63.6
23              1.8               1  城市C    58.0
24              8.2               0  城市C    48.3
25              6.3               1  城市A    68.4
26              4.6               0  城市A    38.5
27              2.5               2  城市A    24.9
28              5.0               2  城市A    29.7
29              3.6               0  城市A    41.6
30              7.4               1  城市C    76.9
31             10.0               1  城市B    60.2
32              1.7               1  城市C    56.3
33              8.0               0  城市C    45.2
34              6.1               1  城市A    65.9
35              4.3               0  城市A    36.7

In [6]:
# OneHot Encoding for City
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False) # sparse=False for easier handling
city_encoded = ohe.fit_transform(data[['City']])
city_df = pd.DataFrame(city_encoded, columns=ohe.get_feature_names_out(['City']))
data = pd.concat([data, city_df], axis=1)
data = data.drop('City', axis=1) # Drop original City column
data

YearsExperience  EducationLevel  Salary  City_城市A  City_城市B  City_城市C
0               3.0               0    45.9       1.0       0.0       0.0
1               7.8               1    80.5       0.0       0.0       1.0
2               2.3               2    25.2       1.0       0.0       0.0
3               5.1               2    30.4       1.0       0.0       0.0
4              10.0               1    65.7       0.0       1.0       0.0
5               1.2               1    60.8       0.0       0.0       1.0
6               8.6               0    50.1       0.0       0.0       1.0
7               6.9               1    70.3       1.0       0.0       0.0
8               4.2               0    40.7       1.0       0.0       0.0
9               2.4               2    28.1       1.0       0.0       0.0
10              5.3               2    32.0       1.0       0.0       0.0
11              3.9               0    48.3       1.0       0.0       0.0
12              7.2               1    84.2       0.0       0.0       1.0
13             10.0               1    70.9       0.0       1.0       0.0
14              1.5               1    62.4       0.0       0.0       1.0
15              8.4               0    55.6       0.0       0.0       1.0
16              6.5               1    72.7       1.0       0.0       0.0
17              4.8               0    42.9       1.0       0.0       0.0
18              2.1               2    26.5       1.0       0.0       0.0
19              5.2               2    31.6       1.0       0.0       0.0
20              3.5               0    43.8       1.0       0.0       0.0
21              7.6               1    78.3       0.0       0.0       1.0
22             10.0               1    63.6       0.0       1.0       0.0
23              1.8               1    58.0       0.0       0.0       1.0
24              8.2               0    48.3       0.0       0.0       1.0
25              6.3               1    68.4       1.0       0.0       0.0
26              4.6               0    38.5       1.0       0.0       0.0
27              2.5               2    24.9       1.0       0.0       0.0
28              5.0               2    29.7       1.0       0.0       0.0
29              3.6               0    41.6       1.0       0.0       0.0
30              7.4               1    76.9       0.0       0.0       1.0
31             10.0               1    60.2       0.0       1.0       0.0
32              1.7               1    56.3       0.0       0.0       1.0
33              8.0               0    45.2       0.0       0.0       1.0
34              6.1               1    65.9       1.0       0.0       0.0
35              4.3               0    36.7       1.0       0.0       0.0

In [7]:
# Prepare data for model
x = data.drop('Salary', axis=1)
y = data['Salary']
x, y

(    YearsExperience  EducationLevel  City_城市A  City_城市B  City_城市C
 0               3.0               0       1.0       0.0       0.0
 1               7.8               1       0.0       0.0       1.0
 2               2.3               2       1.0       0.0       0.0
 3               5.1               2       1.0       0.0       0.0
 4              10.0               1       0.0       1.0       0.0
 5               1.2               1       0.0       0.0       1.0
 6               8.6               0       0.0       0.0       1.0
 7               6.9               1       1.0       0.0       0.0
 8               4.2               0       1.0       0.0       0.0
 9               2.4               2       1.0       0.0       0.0
 10              5.3               2       1.0       0.0       0.0
 11              3.9               0       1.0       0.0       0.0
 12              7.2               1       0.0       0.0       1.0
 13             10.0               1       0.0       1.0      

In [8]:
# 分割資料
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=76) #random_state for reproducibility
x_train, x_test, y_train, y_test

(    YearsExperience  EducationLevel  City_城市A  City_城市B  City_城市C
 21              7.6               1       0.0       0.0       1.0
 19              5.2               2       1.0       0.0       0.0
 6               8.6               0       0.0       0.0       1.0
 17              4.8               0       1.0       0.0       0.0
 28              5.0               2       1.0       0.0       0.0
 23              1.8               1       0.0       0.0       1.0
 31             10.0               1       0.0       1.0       0.0
 4              10.0               1       0.0       1.0       0.0
 30              7.4               1       0.0       0.0       1.0
 3               5.1               2       1.0       0.0       0.0
 16              6.5               1       1.0       0.0       0.0
 5               1.2               1       0.0       0.0       1.0
 20              3.5               0       1.0       0.0       0.0
 32              1.7               1       0.0       0.0      

In [9]:
# Feature Scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

x_train, x_test

(array([[ 0.88230693,  0.0949158 , -1.15470054, -0.2773501 ,  1.34164079],
        [-0.06786976,  1.42373699,  0.8660254 , -0.2773501 , -0.74535599],
        [ 1.27821389, -1.23390539, -1.15470054, -0.2773501 ,  1.34164079],
        [-0.22623255, -1.23390539,  0.8660254 , -0.2773501 , -0.74535599],
        [-0.14705116,  1.42373699,  0.8660254 , -0.2773501 , -0.74535599],
        [-1.41395342,  0.0949158 , -1.15470054, -0.2773501 ,  1.34164079],
        [ 1.83248363,  0.0949158 , -1.15470054,  3.60555128, -0.74535599],
        [ 1.83248363,  0.0949158 , -1.15470054,  3.60555128, -0.74535599],
        [ 0.80312554,  0.0949158 , -1.15470054, -0.2773501 ,  1.34164079],
        [-0.10746046,  1.42373699,  0.8660254 , -0.2773501 , -0.74535599],
        [ 0.44680928,  0.0949158 ,  0.8660254 , -0.2773501 , -0.74535599],
        [-1.65149759,  0.0949158 , -1.15470054, -0.2773501 ,  1.34164079],
        [-0.74091159, -1.23390539,  0.8660254 , -0.2773501 , -0.74535599],
        [-1.45354411,  0.

In [10]:
# 使用線型模型訓練
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [11]:
# 使用測試集測試
y_pred = model.predict(x_test)
y_pred

array([62.95      , 62.95      , 34.29604001, 43.38062826, 42.36724437,
       46.31204031, 52.62478283, 71.73447035])

In [12]:
# 評估模型(example: R-squared)
# r2愈接近1愈好
r2 = model.score(x_test, y_test)
print(f"R-squared: {r2}")

R-squared: 0.22095438551903213


In [13]:
# 取得w(權重),b(偏移值)
w = model.coef_
b = model.intercept_
print(f"w: {model.coef_}")
print(f"b: {model.intercept_}")

w: [ 6.39912908 -1.60706903 -4.32188589 -0.37837382  4.66699438]
b: 51.228571428571435


In [15]:



#使用模型
#預測資料: 5.3 碩士以上 城市A

x_real = np.array([[5.3, 2, 1, 0, 0]])
x_real = scaler.transform(x_real)
y_pred = (w * x_real).sum(axis=1) + b
y_pred

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([41.6430732])